# Generated by Django 3.0.6 on 2020-05-30 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(upload_to='')),
                ('profile_bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='userImages')),
                ('image_name', models.CharField(max_length=40)),
                ('image_caption', models.CharField(max_length=20)),
                ('pub_date', models.DateField()),
                ('image_profile_foreign_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instaapp.Profile')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('image_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instaapp.Image')),
            ],
        ),
    ]
