# Generated by Django 3.0.6 on 2020-05-30 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0002_auto_20200530_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_profile_foreign_key',
        ),
    ]
