# Generated by Django 3.0.6 on 2020-06-01 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0003_remove_image_image_profile_foreign_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='image_comment',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
